name:                onyx-wm
version:             0.1.0.0
license:             BSD3

extra-source-files:

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Foo

dependencies:
- base >= 4.7 && < 5
- onyx-core
- containers
- mtl
- split
- microlens-platform
- non-empty-zipper
- monad-loops
- utility-ht
- mmorph

library:
  source-dirs: src
  default-extensions:
  - TupleSections
  - RecordWildCards
  - FlexibleContexts
  - FlexibleInstances
  - MultiParamTypeClasses
  - ConstraintKinds
  - TypeOperators
  - RankNTypes
  - LambdaCase
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Werror

executables:
  onyx-wm-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - onyx-wm
